// Generated by integration/mainui-home/catalogue.py; regenerate with byte maps.
#pragma once
struct HomePackageBinary { const char* name; const char* hash; };
static const HomePackageBinary homePackageBinaries[]={
    {"MainUI-283-clean","cf3ecb2b0f8e3d1381aab128d61ef9fd5c1f3f874b0c81f4d2efbefc392aa979"},
    {"MainUI-283-expert","9ec75ea47eef114edf3582a452e4562034ed54d6417310d8e2d653a4ceec461f"},
    {"MainUI-354-clean","8746508c500c27c9d8ea07b193f17e9be99548e51533e4df87a64bbbb1a9bc1d"},
    {"MainUI-354-expert","c67c59a881c3b248b6b9b5c0ce0011bcbf4da57a34e8068b8e45d60422bc0ff0"},
};
static const HomePackageBinary homePackageOriginals[]={
    {"MainUI-283-clean","6b01276a6292fd7061e0b2576322a52ada65b755562f97bf7656b174d475866f"},
    {"MainUI-283-expert","6948b5310dda6513b9e8fa2519d90c5287fc1fd06b4f668a7f2f205406281d28"},
    {"MainUI-354-clean","98c85f6c573bdeabd3762e8d9b596f354014e666cc873d0f758cbf3752620c94"},
    {"MainUI-354-expert","3bd1fef7fd9bd215bb9e335b6be1101fdff510590ba0d9ca0a9707edc5d9718a"},
};
static const char homeOriginalRuntime[]="a8d77dcd316bc2a323b1e015aaf4b7682d2fed677af9cdadbc00e48881425d6e";
static const char homeReturnRuntime[]="4e7fdcb04dd53eefbc54a5244e35dbd746681ac77b8fe55e574c3e7227744df1";
