// Generated by integration/mainui-home/catalogue.py; regenerate with byte maps.
#pragma once
struct HomePackageBinary { const char* name; const char* hash; };
static const HomePackageBinary homePackageBinaries[]={
    {"MainUI-283-clean","a8a9771d02fbc7d13d7be2edf6cebe0d7b806c5b2a25256753bd8ed16f02b08a"},
    {"MainUI-283-expert","e05e855c94a9e7bea702e552672297624b42b7e338df57c0b8bdd240a7978d12"},
    {"MainUI-354-clean","4a96ca03acd4f9a4b1ffd23bcb1586d0ec509b71b3006e5322bd717922e830f4"},
    {"MainUI-354-expert","fb094eb2300562642b7f43436e441b9233694f5263f870b974086e88e3db8c75"},
};
static const char homeOriginalRuntime[]="a8d77dcd316bc2a323b1e015aaf4b7682d2fed677af9cdadbc00e48881425d6e";
static const char homeReturnRuntime[]="4e7fdcb04dd53eefbc54a5244e35dbd746681ac77b8fe55e574c3e7227744df1";
