#!/usr/bin/env python3
"""Regenerate reviewed package hashes, C++ availability constants and byte maps."""
import argparse
import json
from pathlib import Path
import prototype

def generate(inputs,payload,output):
    output=output.resolve()
    build=Path(__file__).resolve().parents[2]/'build'
    if build not in output.parents and not str(output).startswith(('/tmp/','/private/tmp/')):
        raise ValueError('Generated artifacts require a fresh host build/tmp directory')
    output.mkdir(parents=True,exist_ok=False)
    code=payload.read_bytes();patched={}
    for name in prototype.HASHES:
        data,report=prototype.patch((inputs/name).read_bytes(),code)
        folder=output/name;folder.mkdir()
        (folder/name).write_bytes(data)
        (folder/'byte-map.json').write_text(json.dumps(report,indent=2)+'\n')
        patched[name]=report['patched_sha256']
    package=Path(__file__).resolve().parent
    spec=dict(version='M6Home1',payload_sha256=prototype.digest(code),originals=prototype.HASHES,patched=patched)
    (package/'package.json').write_text(json.dumps(spec,indent=2)+'\n')
    runtime=json.loads((package.parent/'onion-return/hashes.json').read_text())
    header='// Generated by integration/mainui-home/catalogue.py; regenerate with byte maps.\n#pragma once\nstruct HomePackageBinary { const char* name; const char* hash; };\nstatic const HomePackageBinary homePackageBinaries[]={\n'
    header+=''.join('    {"'+n+'","'+h+'"},\n' for n,h in patched.items())+'};\n'
    header+='static const char homeOriginalRuntime[]="'+runtime['original_sha256']+'";\n'
    header+='static const char homeReturnRuntime[]="'+runtime['patched_sha256']+'";\n'
    (package.parents[1]/'include/home_integration_package.h').write_text(header)
    print(json.dumps(spec,indent=2))
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--inputs',type=Path,required=True);p.add_argument('--payload',type=Path,required=True);p.add_argument('--output',type=Path,required=True)
    a=p.parse_args();generate(a.inputs,a.payload,a.output)
